# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelAssistant-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Moya/RxSwift'
	pod 'RxSwift'
    pod 'RxCocoa'
    pod 'ObjectMapper'
    pod 'Kingfisher', '~> 4.6'

  # Pods for TravelAssistant-iOS

  target 'TravelAssistant-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
