# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelAssistant-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Moya/RxSwift'
	pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'ObjectMapper', '~> 2.2'

  # Pods for TravelAssistant-iOS

  target 'TravelAssistant-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
